# Generated by Django 6.0.6 on 2026-06-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paper_url',
            field=models.URLField(blank=True, help_text='Link para artigo científico (PDF)'),
        ),
    ]
